openapi: 3.0.3
info:
  title: Rudraksha Store API
  version: 1.0.0
  description: >
    MVP API for catalog, orders, manual UPI payments, meetings, reviews.
servers:
  # IMPORTANT: include the /api/v1 base path to match Express mount
  - url: http://localhost:4000/
    description: Local
tags:
  - name: Health
  - name: Auth
  - name: Catalog
  - name: Owner
  - name: Orders
  - name: Payments
  - name: Meetings
  - name: Reviews
  - name: Settings
